---
apiVersion: "policy/v1"
kind: "PodDisruptionBudget"
metadata:
  name: "kafka-controller-pdb"
  labels: {}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: "kafka-controller"
    matchExpressions: []
