---
apiVersion: "policy/v1"
kind: "PodDisruptionBudget"
metadata:
  name: "haproxy-pdb"
  labels: {}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      nirmata.io/service.name: "haproxy"
    matchExpressions: []
