apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-tls-config
  namespace: nirmata
data:
  mongod.conf: |
    security:
      keyFile: /etc/ssl/mongo/mongodb.key
      authorization: enabled
    net:
      tls:
        mode: requireTLS
        certificateKeyFile: /etc/ssl/mongodb.pem
        CAFile: /etc/ssl/root-ca.pem
        allowConnectionsWithoutCertificates: true
#    net:
#      bindIp: *.mongodb-hs.nirmata.svc.cluster.local
#      port: 27017
