apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"nirmata.io/service.name":"mongodb","nirmata.io/statefulset.name":"mongodb","nirmata.io/type":"data"},"name":"mongodb","namespace":"nirmata"},"spec":{"podManagementPolicy":"OrderedReady","replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"mongodb","nirmata.io/service.name":"mongodb","nirmata.io/statefulset.name":"mongodb","nirmata.io/type":"data"}},"serviceName":"mongodb-hs","template":{"metadata":{"labels":{"app":"mongodb","environment":"production","nirmata.io/service.name":"mongodb","nirmata.io/statefulset.name":"mongodb","nirmata.io/type":"data","replicaset":"nirmata","role":"mongodb"}},"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["mongodb"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"command":["mongod","--wiredTigerCacheSizeGB","60","--bind_ip","0.0.0.0","--replSet","nirmata"],"image":"ghcr.io/nirmata/mongodb:5.0.15","imagePullPolicy":"IfNotPresent","name":"mongodb","ports":[{"containerPort":27017,"protocol":"TCP"}],"resources":{"limits":{"memory":"10Gi"},"requests":{"cpu":"1","memory":"1Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data/db","name":"mongodb-data-volume"}]},{"env":[{"name":"MONGO_SIDECAR_POD_LABELS","value":"role=mongodb,environment=production"},{"name":"KUBE_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"KUBERNETES_MONGO_SERVICE_NAME","value":"mongodb-hs"}],"image":"ghcr.io/nirmata/mongo-k8s-sidecar:5.0.15","imagePullPolicy":"IfNotPresent","name":"mongo-sidecar","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"ghcr.io"}],"priorityClassName":"nirmata-data-critical","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"mongodb","serviceAccountName":"mongodb","terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoSchedule","key":"dedicated","operator":"Equal","value":"mongodb"},{"effect":"NoExecute","key":"node.kubernetes.io/not-ready","operator":"Exists","tolerationSeconds":20},{"effect":"NoExecute","key":"node.kubernetes.io/unreachable","operator":"Exists","tolerationSeconds":20}]}},"updateStrategy":{"type":"RollingUpdate"},"volumeClaimTemplates":[{"metadata":{"name":"mongodb-data-volume"},"spec":{"accessModes":["ReadWriteOnce"],"dataSource":null,"resources":{"requests":{"storage":"20Gi"}},"storageClassName":"azurefile-csi","volumeMode":"Filesystem"}}]}}
  creationTimestamp: "2023-12-13T11:04:59Z"
  generation: 34
  labels:
    nirmata.io/service.name: mongodb
    nirmata.io/statefulset.name: mongodb
    nirmata.io/type: data
  name: mongodb
  namespace: nirmata
  resourceVersion: "384302"
  uid: 68733676-b6fb-4224-89bd-782b69637107
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongodb
      nirmata.io/service.name: mongodb
      nirmata.io/statefulset.name: mongodb
      nirmata.io/type: data
  serviceName: mongodb-hs
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
        environment: production
        nirmata.io/service.name: mongodb
        nirmata.io/statefulset.name: mongodb
        nirmata.io/type: data
        replicaset: nirmata
        role: mongodb
    spec:
      containers:
      - args:
        - --config
        - /etc/mongo/mongod.conf
        command:
        - mongod
        - --wiredTigerCacheSizeGB
        - "60"
        - --bind_ip
        - 0.0.0.0
        - --replSet
        - nirmata
        image: ghcr.io/nirmata/mongodb:5.0.15
        imagePullPolicy: IfNotPresent
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        resources:
          limits:
            memory: 10Gi
          requests:
            cpu: "1"
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-data-volume
        - mountPath: /etc/mongo
          name: mongo-tls-config
        - mountPath: /etc/ssl
          name: mongo-ssl-certs
        - mountPath: /etc/ssl/mongo
          name: mongo-key
          readOnly: true
      - env:
        - name: MONGO_SIDECAR_POD_LABELS
          value: role=mongodb,environment=production
        - name: KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_MONGO_SERVICE_NAME
          value: mongodb-hs
        image: ghcr.io/nirmata/mongo-k8s-sidecar:5.0.15
        imagePullPolicy: IfNotPresent
        name: mongo-sidecar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcr.io
      priorityClassName: nirmata-data-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: mongodb
      serviceAccountName: mongodb
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: mongodb
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 20
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 20
      volumes:
      - configMap:
          defaultMode: 420
          name: mongo-tls-config
        name: mongo-tls-config
      - name: mongo-ssl-certs
        secret:
          defaultMode: 420
          secretName: mongo-ssl-certs
      - name: mongo-key
        secret:
          defaultMode: 256
          secretName: mongo-key
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: mongodb-data-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: azurefile-csi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: mongodb-f86659ffd
  observedGeneration: 34
  readyReplicas: 3
  replicas: 3
  updateRevision: mongodb-f86659ffd
  updatedReplicas: 3
